### ISSUE TITLE
ios 编译提示 无法找到 CAPPluginCall

### ISSUE THREAD

**Issue by wangcode** [veluxa/capacitor-plugin-pay#1]
ios 编译提示 无法找到 CAPPluginCall
引入Capacitor后提示 Framework not found CordovaPlugins

**Comment by veluxa** [comment]
你没有添加Capacitor依赖

**Comment by wangcode** [comment]
@veluxa 
解决了，另外不知道是不是capacitor插件更新的原因，插件内的 AppDelegate.swift 并没有被执行，导致微信没有被注册，我非常非常不懂ios开发，所以不太清楚，我把注册部分代码写在onload里了
